jwt.secret=ChangeThisSecretKey
jwt.expiration-ms=86400000
jwt.refresh-expiration-ms=604800000
app.reset-token-expiration-minutes=30
# Dominio(s) del frontend permitido; ajusta `https://frontdev-campus.upsjb.edu.pe` al dominio real en producción
app.cors.allowed-origins=http://localhost:4200,https://frontdev-campus.upsjb.edu.pe
